module.exports = {
  docs: [
    'Home',
    {
      type: 'category',
      label: '电路设计',
      items: [
        'AirForce-充满灵性的电机驱动模块',
        '如何设计一款单片机的最小系统',
        'SwiftCtrl-蓝牙手柄',
        'TinyDVR-小巧身材，满载动力',
        'ZenDriver-高性能的电机驱动',
        'PCB布线规范',
        'PCB元件布局规范',
        'PCB线宽与电流的关系',
        '函数思想在电路设计中的应用',
        '基本元器件选型',
        '锂电池的选型',
        '电源的设计',
        'AD小技巧整理',
        'AD入门系列一：环境搭建',
        'AD入门系列二：基础知识',
        'AD入门系列三：原理图绘制',
        'AD入门系列四：PCB绘制',
        'AD入门系列五：库文件绘制',
        '自制CMSIS-DAP',
        'PCB名片设计',
        '常用的防反接电路',
        '什么是金手指',
        '电路设计中常用的接口及关键点',
        'AD使用Git的注意事项',
      ],
    },

    {
      type: 'category',
      label: '队务管理',
      items: [
        '团队知识库的搭建-理论',
        '动员大会-经验总结',
        '换届大会-经验总结',
        '破冰活动-经验总结',
        '出展活动-经验总结',
      ],
    },
    {
      type: 'category',
      label: '嵌入式开发',
      items: [
        'C与STM32常用宏定义',
        'SWD与JTAG的区别与联系',
        'HAL库开发笔记（一）-环境配置',
        'HAL库开发笔记（二）-GPIO',
        'HAL库开发笔记（三）-外部中断',
        'HAL库开发笔记（四）-串口通信',
        'PlatformIO—一站式嵌入式开发工具',
        'PlatformIO搭配CubeMX食用',
        'CubeMX的一些坑',
        'STM32的启动模式',
        'KeilMDK配置指南',
        '大疆N3飞控-参考资料',
        'ATTiny85调试记录',
        'T-Clock桌上小钟',
        '麦轮小车',
        '一个舵机的自我修养',
      ],
    },

    {
      type: 'category',
      label: '高效工作',
      items: [
        '个人数字资产永久保存指南',
        '如何用Markdown写学术论文',
        '为什么你需要一个知识库',
        '个人文案排版规范',
        '个人知识库的搭建-基于Docusaurus',
        'Windows初始化与软件推荐',
        'Docusaurus极简部署指南',
        'Hugo极简搭建指南',
        '如何在iPad上运行VSCode',
        '使用Markdown进行高效写作',
        '用树莓派架设云打印服务器',
        '用Graphviz绘制关系图',
        'RSS-高效率的阅读方式',
        '把回忆放心交给GooglePhotos',
        'VSCode生产力指南-环境配置',
        'VSCode生产力指南-JupyterNotebook',
        '在浏览器上运行VSCode（旧）',
        '如何配一台电脑',
        '用reveal.js制作幻灯片',
      ],
    },
    {
      type: 'category',
      label: '软件开发',
      items: [
        '机器视觉入门',
        '使用R语言进行数据分析',
        'CSS学习笔记',
        'HTML学习笔记',
        'JavaScript学习笔记',
        'Docker简易指南',
        'DockerCompose-更优雅的打开方式',
        '自适应网页设计',
        '前端开发-环境搭建',
        'BookJourney-二手书商城小程序',
        'Git学习笔记',
      ],
    },


    {
      type: 'category',
      label: '产品经理',
      items: [
        '产品经理的日常',
        '中台的概念',
        '画图基础',
        '智能硬件产品经理的技术要求',
        '如何撰写一份BRD',
        '软件开发中的注意事项',
        '专业与分工',
        '关于复盘',
      ],
    },
    {
      type: 'category',
      label: '生活',
      items: [
        '如何调制一杯鸡尾酒',
        '如何合理配置个人资产',
        '读《黑客与画家》',
        '英语六级-备考',
        '音乐相关',
        '谈谈未来的职业选择',
        'THEHack2019黑客马拉松',
        'Hack.init()黑客马拉松',
        '焊接大赛培训及总结',
        '为什么要「站在巨人的肩膀上」',
        '如何不被AI取代',
        '一些观点',
      ],
    },

    {
      type: 'category',
      label: '小技巧',
      items: [
        '使用gitignore忽略特殊文件',
        '3D打印：ABS与PLA的区别',
        '如何批量拉取Git仓库更新',
        '如何用Markdown写公众号文章',
        '如何快速删除node_modules',
        '如何为公众号文章增加特效',
        '如何在Linux下使用微信',
        '如何打印出手写效果的文字',
        '如何从乐曲中分离音轨',
        '如何高效制作幻灯片',
        '卡片式写作',
        'npm和Yarn换源加速国内访问',
        'Vue.js小技巧',
        '正则表达式实用语句',
        'LaTeX希腊字母对照表',
        'GitHub改Host',
        'Linux用户操作',
        'MSI主板开启虚拟化的方法',
        'Git配置代理',
        '删除GitHub仓库中某个文件夹',
        '定制SublimeText3',
        '如何保存易逝的文字',
        '用Vercel加速Pages服务',
        'Doxygen注释规范',
        'AltiumDesigner安装库文件',
        'CentOS配置OhMyZsh',
        '如何快速制作一个启动盘',
        '使用VSCode进行远程开发',
        'Node.js和npm的安装与卸载（MacOS）',
      ],
    },

  ],
};

// 归档：
//'archive/Python学习笔记',
//'archive/STM32麦轮小车',
//'archive/RM校内赛-前期策划',
//'archive/报告书都要写些什么？',
//'archive/无人驾驶比赛',
//'archive/硬件模块',
//'archive/命令行基本操作'
//'archive/科技X的访谈',
//'archive/极简面包-烘培',

//'archive/Bash基础',
//'archive/Linux基础（CentOS）',
//'archive/从零搭建视觉开发环境（Docker-Linux）',
//'archive/Excel批量激活链接并转为图片',
//'archive/智能硬件产品开发流程',
//'archive/华广爬楼指北',
//'archive/小车游华广-比赛',
//'archive/麦昆小车-测评',
//'archive/STM32模块设计-LED',
//'archive/团队公开知识库的搭建',

// 未列出文章：
//'unlist/CentOS安装Docker',
//'unlist/Docker方式运行code-server',
//'unlist/T-Clock桌上小钟（旧）',
//'unlist/构建知识管理系统',
//'unlist/回归博客',
//'unlist/团队知识库搭建记录-DokuWiki',
//'unlist/个人知识库极简搭建指南-VuePress',
//'unlist/博客转至GitBook',
//'unlist/浅谈Bitcron博客平台',
//'unlist/基于docsify搭建个人Wiki',